const fields = [
    { name: "Name", type: "name", showname: "Patiend Name", required: 0 },
    { name: "Age", type: "number", showname: "Age", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "BMI", type: "number", showname: "Body Mass Index", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "Maximal_tumor_size", type: "number", showname: "Maximal Tumor Size (cm)", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "Total_bilirubin", type: "number", showname: "Total Bilirubin", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "GPT", type: "number", showname: "GPT", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "AFP", type: "number", showname: "AFP", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "INR", type: "number", showname: "INR", retsrict:"float", range:[0, 38640], required: 1 },
    { name: "Hemoglobin", type: "number", showname: "Hemoglobin", retsrict:"float", range:[], required: 1 },
    { name: "Albumin", type: "number", showname: "Albumin", retsrict:"float", range:[], required: 1 },
    { name: "Creatine", type: "number", showname: "Creatine", retsrict:"float", range:[], required: 1 },
    { name: "Platelet_count", type: "number", showname: "Platelet Count", retsrict:"float", range:[], required: 1 },
    { name: "ChildPugh_score", type: "number", showname: "Child-Pugh Score", retsrict:"float", range:[], required: 1 },
    { name: "PS", type: "select", showname: "Performance Status (PS)", choice: {"正常": 0, "輕微不便":1, "行動不便":2, "坐輪椅":3, "躺床":4}, required: 1 },
    { name: "ChildPugh_class", type: "select", showname: "Child-Pugh Class", choice: {"A":0, "B":1, "C":2}, required: 1 },
    { name: "Sex", type: "select", showname: "Sex", retsrict:"float", choice: {"男":0, "女":1}, required: 1 },
    { name: "Tumor_number", type: "select", showname: "Tumor Number", choice: {"單顆腫瘤":0, "多顆腫瘤":1}, required: 1 },
    { name: "Tumor_distribution", type: "select", showname: "Tumor Distribution", choice: {"成對":0, "單側":1}, required: 1 },
    { name: "Encephalopathy", type: "select", showname: "Encephalopathy", choice: {"無":0, "輕微":1, "嚴重":2}, required: 1 },
    { name: "Ascites", type: "select", showname: "Ascites", choice: {"無":0, "輕微":1, "嚴重":2}, required: 1 },
    { name: "HBV", type: "boolean", showname: "HBV", required: 0 },
    { name: "HCV", type: "boolean", showname: "HCV", required: 0 },
    { name: "Lymphonodules", type: "boolean", showname: "Lymphonodules", required: 0 },
    { name: "EHS", type: "boolean", showname: "Extrahepati Spread (EHS)", required: 0 },
    { name: "MVI", type: "boolean", showname: "Macrovascular Invasion (MVI)", required: 0 },
    { name: "Cirrhosis", type: "boolean", showname: "Cirrhosis", required: 0 },
    { name: "DM", type: "boolean", showname: "DM", required: 0 },
    { name: "HTN", type: "boolean", showname: "HTN", required: 0 },
    { name: "ESRD", type: "boolean", showname: "ESRD", required: 0 },
    { name: "CKD", type: "boolean", showname: "CKD", required: 0 },

    // v2: choose therapy by user is depreciated in api_v2.
    // { name: "Liver_transplantation", type: "boolean", showname: "Liver Transplantation" },
    // { name: "Surgical_resection", type: "boolean", showname: "Surgical Resection" },
    // { name: "Radiofrequency", type: "boolean", showname: "Radiofrequency" },
    // { name: "TACE", type: "boolean", showname: "TACE" },
    // { name: "Target_therapy", type: "boolean", showname: "Target Therapy" },
    // { name: "Immunotherapy", type: "boolean", showname: "Immunotherapy" },
    // { name: "HAIC", type: "boolean", showname: "HAIC" },
    // { name: "Radiotherapy", type: "boolean", showname: "Radiotherapy" },
    // { name: "Best_support_care", type: "boolean", showname: "Best Support Care" },
    // { name: "S_T", type: "boolean", showname: "S and T" },
    // { name: "R_T", type: "boolean", showname: "R and T" },
];

export default fields;